### ISSUE TITLE
Does FLux support redaction.

### ISSUE THREAD

**Issue by dixitsingla** [marklogic/flux#244]
In the current project, redaction is done through MLCP(gradle), by passing `args = ["-redaction", "$ruleset"]` in the COPY command.
I was just exploring this new software and thought of using it in redaction project, do we have redaction option available in flux?

**Comment by rjrudin** [comment]
Hi @dixitsingla  - while MLCP has special handling for redaction, that doesn't yet exist via the MarkLogic REST API, which is what Flux depends on. You would instead need to create a REST transform that uses the redaction library directly, either via JavaScript or XQuery - see https://docs.marklogic.com/guide/app-dev/redaction#id_42292 . If we do enhance the REST API to provide first-class support for redaction rulesets, we will definitely expose that via Flux as well.

**Comment by dixitsingla** [comment]
Is there any guide/example how to use the API in flux.

**Comment by rjrudin** [comment]
Yes - see https://marklogic.github.io/flux/api.html , along with the Javadocs at https://marklogic.github.io/flux/assets/javadoc/com/marklogic/flux/api/package-summary.html .

**Comment by rjrudin** [comment]
We're about to add an example to the Flux docs - #247 - for implementing a REST transform using the MarkLogic redaction library. For any REST API client, such as Flux, that's the best approach. So closing this ticket, though once we have support in the REST API for specifying a ruleset in a manner similar to that in Flux, we'll add it a command-line option for it right away to Flux.
