### ISSUE TITLE
The download for the example app zip appears to be missing from the releases page

### ISSUE THREAD

**Issue by freeweel** [marklogic/flux#257]
In the Getting Started guide, it says to download these zips from the release page:
1. Download marklogic-flux-1.0.0.zip0
2. Download the example application marklogic-flux-getting-started-1.0.0.zip

I was able to download flux, but there is no reference to the zip with the example app on the releases page.

How might I get this file?

**Comment by rjrudin** [comment]
Thanks @freeweel  for the heads' up - everything is automated for building the artifacts, but still gotta remember to attach them to the release! The example zip is now at https://github.com/marklogic/flux/releases/tag/1.0.0 .
