### ISSUE TITLE
Export archive failed with XDMP-OLDSTAMP error

### ISSUE THREAD

**Issue by freeweel** [marklogic/flux#266]
I have been trying flux out, and I ran it on SC DHHS 9 node cluster to see how it handles larger loads.  The member collection has about 1.4 million docs, and flux reported that it ran with 36 partitions.   On the final DB flux succeeded to archive the files in about 24 minutes, but on the staging DB I got the following error on multiple runs when it hit about 0.5 million.   Ran the same archive using MLCP and it succeeded.   Also tried merging the DB and re-running flux -- same error.

_Command failed, cause: SparkException: Job aborted due to stage failure: Task 12 in stage 0.0 failed 1 times, most recent failure: Lost task12.0 in stage 0.0 (TID 12) (ip-10-3-104-8.ec2.internal executor driver): com.marklogic.client.FailedRequestException: Local message: failed to read resource at internal/uris: Internal Server Error. Server Message: XDMP-OLDSTAMP: Timestamp too old for forest RDL-9 (17283146413824010 < 17283147612451500; 17283153612451500)_

Here is the command used:

/flux export-archive-files \
    --connection-string "pvanderveen:XXXXXXX@marklogic.perf.scdhhs.online:8100" \
    --ssl-protocol TLSv1.2 \
    --collections member \
    --batch-size 100 \
    --path ./archive/member

**Comment by rjrudin** [comment]
We're adding docs for the current solution for this, which is to adjust the merge timestamp for the database. 

But we are looking at two separate enhancements:

1. Allowing for a "dirty read" by not using a snapshot. 
2. Using the REST transaction API as a means of guaranteeing that the server timestamp will not be discarded. 

Closing this as the immediate issue has been solved, there's a docs PR open, and we'll have internal tickets for the above two items.
